Attribute VB_Name = "modInfoAbout"
' modInfoAbout
' 2000/06/11 Copyright © 2000, Larry Rebich
' 2000/06/11 larry@buygold.net, www.buygold.net, 760.771.4730

    Option Explicit
    DefLng A-Z
    
    Public Const gcsCompany = "BuyGold"         'my company
    Private Const gcsHome = "www.buygold.net"   'my domain
    Private Const gcsTipsURL = "http://" & gcsHome & "/tips"    '2002/07/06
    '


Public Sub DoAbout(frm As Form)
'-------------------------------------------------------------------------------
' 1998/07/28 12:50:13, Code generated by TBMsgBox 5.07, a product of The Bridge, Inc.
    Dim sMBVB_Msg As String         'The Message is passed in this variable
    Dim sMBVB_Title As String       'The Title is passed in this variable
    Dim lMBVB_Type As Long          'Icon information, number of buttons, etc. is passed in this long integer
    sMBVB_Msg = "Copyright " & Chr(169) & " " & Format$(Date, "yyyy") & vbCr
    sMBVB_Msg = sMBVB_Msg & vbCr
    sMBVB_Msg = sMBVB_Msg & "Larry Rebich" & vbCr
    sMBVB_Msg = sMBVB_Msg & vbCr
    sMBVB_Msg = sMBVB_Msg & "larry@larryrebich.com" & vbCr
    sMBVB_Msg = sMBVB_Msg & "www.larryrebich.com" & vbCr
    sMBVB_Title = FormatVersion()
    lMBVB_Type = vbInformation

    MsgBox sMBVB_Msg, lMBVB_Type, sMBVB_Title
'-------------------------------------------------------------------------------
End Sub

Private Function FormatVersion() As String
' 1998/07/29 Format version information for Help/About
    Dim sTemp As String
        With App
            sTemp = .ProductName & " "
            sTemp = sTemp & Format$(.Major, "0000") & "."
            sTemp = sTemp & Format$(.Minor, "00") & "."
            sTemp = sTemp & Format$(.Revision, "00")
        End With
    FormatVersion = sTemp
End Function

Public Sub DoInfo(frm As Form, iVolume As Integer, iNumber As Integer)
    Dim sBrowserExec As String
    Dim sURL As String
    Dim sVolNum As String
    
    Const mcsUnableToConnect = " Unable to Connect"
    
    sVolNum = "v" & Format$(iVolume, "00") & "n" & Format$(iNumber, "00")
    sVolNum = "/" & sVolNum & "/" & sVolNum & ".html"
    
    sBrowserExec = GetBrowserExe        'get the exe
    If sBrowserExec <> "" Then
        sURL = gcsHome & sVolNum
        If ConnectToWebSite(frm, sBrowserExec, sURL) Then    'launch browser
        Else
            MsgBox "Unable to open " & sURL & ".", vbExclamation, mcsUnableToConnect
        End If
    Else
        MsgBox "Could not find a browser.", vbExclamation, mcsUnableToConnect
    End If
End Sub

Public Sub DoTips()
' 2002/07/06 Sub created by Larry Rebich while in Whitefish, MT.
    OpenURL gcsTipsURL
End Sub
